before_install:
  - sudo mysql -e 'drop database if exists employe_bugs;'
  - sudo mysql -e 'crate database employe_bugs;'
  - sudo mysql < "tables.sql"
  - sudo mysql < "populate.sql"
jdk:
  - oraclejdk15
language: java
sudo: enabled
services:
  - mysql
script: mvn clean test
