
before_script:
   - "mysql -e 'CREATE DATABASE IF NOT EXISTS employe_bugs;use employe_bugs;

create table if not exists employee
(employee_id int unique not null auto_increment,
emp_name varchar(50),
emp_position varchar(50),
PRIMARY  KEY(employee_id)
);'"
install: true
jdk:
   - oraclejdk15
language: java
packages:
   - oracle-java8-installer
script:
   - "mvn install"
services:
   - mysql
