before_install: 
  
  - sudo mysql < "tables.sql"
  - sudo mysql < "populate.sql"
mysql:
    username: root
    password: dsmodoc
jdk: 
  - oraclejdk15
language: java
script: "mvn clean test"
services: 
  - mysql
sudo: enabled
