before_install: 
  - sudo mysql -u root --password="dsmodoc";
  - sudo mysql -e 'drop database if exists employe_bugs;'
  - sudo mysql -e 'create database employe_bugs;'
  - sudo mysql < "tables.sql"
  - sudo mysql < "populate.sql"
jdk: 
  - oraclejdk15
language: java
script: "mvn clean test"
services: 
  - mysql
sudo: enabled
